name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['*']

jobs:
  build_and_test:
    name: LNDK Rust Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      #- uses: actions-rs/cargo@v1
      #  name: cargo build
      #  with:
      #    command: build
      #    args: --release --all-features
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: --all-targets --benches
      - run: ls /tmp
      - name: Archive lnd logs
        uses: actions/upload-artifact@v3
        with:
          name: lnd-logs
          path: |
            /tmp/lnd_logs
      - uses: actions-rs/cargo@v1
        name: cargo fmt
        with:
          command: fmt
          args: --check
      - uses: actions-rs/cargo@v1
        name: cargo clippy
        with:
          command: clippy
          args: -- --deny warnings






#      - name: TESTING_2
#         run: |
#           ls
#           ls /tmp
